services:
  redis:
    build:
      context: .
      dockerfile: redis.dockerfile
    container_name: redis_bot_app
    restart: unless-stopped
    user: redis
    ports:
      - 6380:6380
    volumes:
      - redis_data:/data
      - ./src/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - bdocs_main_6797

  db:
    image: postgres:latest
    container_name: bdocs_main_6797_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    networks:
      - bdocs_main_6797

  app:
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: bdocs_main_6797
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - bdocs_main_6797

  auth:
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: bdocs_auth
    env_file:
      - .env
    volumes:
      - .:/app
    command: "poetry run python get_dialogs.py"
    networks:
      - bdocs_main_6797

volumes:
  redis_data:
  postgres_data:

networks:
  bdocs_main_6797:
