services:
  redis:
    build:
      context: .
      dockerfile: redis.dockerfile
    container_name: redis_bot_app
    restart: unless-stopped
    user: redis
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data
      - ./src/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: bdocs_main_6797
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - app_network

  auth:
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: bdocs_auth
    env_file:
      - .env
    volumes:
      - .:/app
    command: "poetry run python get_dialogs.py"
    networks:
      - app_network

volumes:
  redis_data:

networks:
  app_network:
    external: true