"""empty message

Revision ID: 2333d25fab40
Revises: f120beeba2d7
Create Date: 2024-10-19 12:44:32.164769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2333d25fab40'
down_revision: Union[str, None] = 'f120beeba2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifts', 'managers',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=25),
               existing_nullable=False)
    op.add_column('users', sa.Column('folder', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'folder')
    op.alter_column('shifts', 'managers',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
