"""empty message

Revision ID: f120beeba2d7
Revises: 9e857c6bacda
Create Date: 2024-10-13 16:00:54.114844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f120beeba2d7'
down_revision: Union[str, None] = '9e857c6bacda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('managers', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('shifts', 'managers',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=25),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifts', 'managers',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_table('managers')
    # ### end Alembic commands ###
