"""init

Revision ID: 0edb5ade6931
Revises: 
Create Date: 2025-01-06 17:42:24.774538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0edb5ade6931'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('card', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=False, comment='Card like 1234567891234567'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('card')
    )
    op.create_table('managers_list',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('prefix_name', sa.String(length=16), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix_name')
    )
    op.create_table('shifts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('registration_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('get_message', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('folder', sa.String(length=16), nullable=True),
    sa.Column('ping_step', sa.String(length=16), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managers_shifts',
    sa.Column('shift_id', sa.BIGINT(), nullable=False),
    sa.Column('manager_id', sa.BIGINT(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers_list.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('shift_id', 'manager_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('managers_shifts')
    op.drop_table('users')
    op.drop_table('shifts')
    op.drop_table('managers_list')
    op.drop_table('cards')
    # ### end Alembic commands ###
