"""empty message

Revision ID: 9e857c6bacda
Revises: 8aa3829ca02e
Create Date: 2024-10-07 22:32:23.243038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e857c6bacda'
down_revision: Union[str, None] = '8aa3829ca02e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifts', 'managers',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=25),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifts', 'managers',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###
