"""empty message

Revision ID: de580f8edaf3
Revises: 498ce392fca6
Create Date: 2024-08-19 15:12:37.578535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de580f8edaf3'
down_revision: Union[str, None] = '498ce392fca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('managers', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shifts')
    # ### end Alembic commands ###
