"""empty message

Revision ID: e0bf37d0a436
Revises: de580f8edaf3
Create Date: 2024-09-12 17:06:29.116314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0bf37d0a436'
down_revision: Union[str, None] = 'de580f8edaf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('card', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=False, comment='Card like 1234567891234567'),
    sa.PrimaryKeyConstraint('card')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
