from .daily_folders_manager import DailyFoldersManagerInterface
from .folder_statistics_manager import FolderStatisticsInterface
from .folder_utils_manager import FolderUtilsInterface
from .telegram_folder_manager import AllManagersFactoryInterface
from .dialog_manager import DialogManagerInterface
